### PR TITLE
Better hygiene for `core` crate naming (#180)

### LINKED ISSUE #180: `cargo test` fails in package named "core"
In the following project,

* `Cargo.toml`:
```
[workspace]
members = ["core"]
```
* `core/Cargo.toml`:
```
[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
```
* `core/src/lib.rs`:
```
use derive_more::Add;

#[derive(Add)]
pub struct Foo(u32);
```
... `cargo check` works fine, but `cargo test` gives:
```
error[E0433]: failed to resolve: could not find `ops` in `core`
 --> /home/xxx/core/src/lib.rs:3:10
  |
3 | #[derive(Add)]
  |          ^^^ could not find `ops` in `core`
  |
  = note: this error originates in the derive macro `Add` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
```

`cargo test` works fine if package is not named `core`.

### PR DESCRIPTION
**Pull request by tyranron**
Resolves #180

## Synopsis

See https://github.com/JelteF/derive_more/issues/180#issue-1091650576 for details.

At the moment, compilation fails in a local crate `core` is present in workspace or some another crate is renamed as `core`.

## Solution

Use `::derive_more::core` instead of `::core` in macro expansions.

## Checklist

- [x] ~~Documentation is updated~~ (not required)
- [x] ~~Tests are added/updated~~ (hard to test)
- [x] [CHANGELOG entry][l:1] is added

[l:1]: /CHANGELOG.md

### CODE REVIEW

File: impl/src/add_assign_like.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ pub fn expand(input: &DeriveInput, trait_name: &str) -> TokenStream {
 
     quote! {
         #[automatically_derived]
-        impl #impl_generics ::core::ops::#trait_ident for #input_type #ty_generics #where_clause {
+        impl #impl_generics ::derive_more::core::ops::#trait_ident for #input_type #ty_generics #where_clause {
```
Comment (JelteF) [inline impl/src/add_assign_like.rs:32]: We're re-exporting these traits now right. Any reason we cannot do:

```suggestion
        impl #impl_generics ::derive_more::#trait_ident for #input_type #ty_generics #where_clause {
```

File: src/lib.rs [hunk 2]
```diff
@@ -48,6 +48,12 @@
 #![forbid(non_ascii_idents, unsafe_code)]
 #![warn(clippy::nonstandard_macro_braces)]
 
+// For macro expansion internals only.
+// Ensures better hygiene in case a local crate `core` is present in workspace of the user code,
+// or some other crate is renamed as `core`.
+#[doc(hidden)]
+pub use core;
```
Comment (JelteF) [inline src/lib.rs:55]: Honestly, I don't think this is worth all this. I think the advice: "don't call your crate core" is good enough.

File: impl/src/add_assign_like.rs (hunk 1 above)
Comment (tyranron) [reply impl/src/add_assign_like.rs]: @JelteF I've stripped redundant paths where possible.

File: src/lib.rs (hunk 2 above)
Comment (tyranron) [reply src/lib.rs:55]: @JelteF we already had that episodically here and there across the code base. I don't see any downsides of this, and it doesn't cost us anything, except making the codebase a little bit more consistent.

Comment (JelteF) [reply src/lib.rs:55]: This basically starts including all of std in our API surface. Can you check if that has impact on compile times or crate size?

Comment (tyranron) [reply src/lib.rs:55]: @JelteF hmm... I don't think that `use` statements actually _include_ something into crate, rather than just making outside types nameable or accessible from other crates. Furthermore, every Rust toolchain has the `core` lib being precompiled already there. So it's only up to LTO to eliminate redundant code in the final binary.

Anyway, running
```bash
cargo bloat --example deny_missing_docs --features full --profile release --crates --split-std
```

Shows on `master`:
```
 File  .text     Size Crate
12.1%  28.3%  58.6KiB std
11.2%  26.1%  54.2KiB core
 7.2%  16.9%  35.1KiB gimli
 5.3%  12.3%  25.5KiB addr2line
 4.6%  10.7%  22.1KiB rustc_demangle
 2.1%   5.0%  10.3KiB [Unknown]
 1.8%   4.2%   8.7KiB alloc
 0.4%   0.9%   1.9KiB object
 0.2%   0.4%     940B memchr
 0.1%   0.2%     432B trybuild
 0.1%   0.1%     272B panic_abort
 0.0%   0.1%     124B basic_toml
 0.0%   0.0%      24B panic_unwind
 0.0%   0.0%       8B libc
 0.0%   0.0%       4B deny_missing_docs
42.8% 100.0% 207.3KiB .text section size, the file size is 484.1KiB

```

And on this branch:
```
 File  .text     Size Crate
12.1%  28.3%  58.6KiB std
11.2%  26.1%  54.2KiB core
 7.2%  16.9%  35.1KiB gimli
 5.3%  12.3%  25.5KiB addr2line
 4.6%  10.7%  22.1KiB rustc_demangle
 2.1%   5.0%  10.3KiB [Unknown]
 1.8%   4.2%   8.7KiB alloc
 0.4%   0.9%   1.9KiB object
 0.2%   0.4%     940B memchr
 0.1%   0.2%     432B trybuild
 0.1%   0.1%     272B panic_abort
 0.0%   0.1%     124B basic_toml
 0.0%   0.0%      24B panic_unwind
 0.0%   0.0%       8B libc
 0.0%   0.0%       4B deny_missing_docs
42.8% 100.0% 207.3KiB .text section size, the file size is 484.1KiB
```

Which doesn't show any meaningful difference.

And for the timings...

`master`:
```
$ cargo bloat --example deny_missing_docs --features full --profile release -j 1 --split-std --time
 Time Crate
9.23s trybuild
2.28s derive_more_impl
1.49s serde_json
1.48s serde_derive
1.38s syn
1.38s serde
1.26s basic_toml
0.53s glob
0.38s rustversion
0.37s proc_macro2
0.28s termcolor
0.26s derive_more
0.17s unicode_segmentation
0.15s convert_case
0.14s ryu
0.11s quote
0.08s once_cell
0.07s deny_missing_docs
0.04s unicode_ident
0.04s itoa
0.02s unicode_xid
0.01s static_assertions
```

this branch:
```
$ cargo bloat --example deny_missing_docs --features full --profile release -j 1 --split-std --time
 Time Crate
9.22s trybuild
2.25s derive_more_impl
1.49s serde_derive
1.47s serde_json
1.36s syn
1.36s serde
1.27s basic_toml
0.53s glob
0.38s rustversion
0.37s proc_macro2
0.28s termcolor
0.25s derive_more
0.16s unicode_segmentation
0.15s convert_case
0.14s ryu
0.11s quote
0.08s once_cell
0.07s deny_missing_docs
0.04s itoa
0.04s unicode_ident
0.03s unicode_xid
0.01s static_assertions
```

File: impl/src/as/mod.rs [hunk 3]
```diff
@@ -239,7 +239,9 @@ impl<'a> ToTokens for Expansion<'a> {
                 ImplKind::Specialized
             };
 
-            let trait_ty = quote! { ::core::convert::#trait_ident <#return_ty> };
+            let trait_ty = quote! {
+                ::derive_more::core::convert::#trait_ident <#return_ty>
```
Comment (JelteF) [inline impl/src/as/mod.rs:243]: Can we use the shorter form here?
```suggestion
                ::derive_more::#trait_ident <#return_ty>
```

File: src/lib.rs (hunk 2 above)
Comment (JelteF) [reply src/lib.rs:55]: I guess this was stupid friday evening thinking of me. Thank you for explaining that this doesn't impact binary size or build time (I guess generating docs would take a lot longer if it wasn't `#[doc(hidden)]` though)

**Review by JelteF — APPROVED** [review]
I called out one place where maybe one we can use the shorter path, other than that this looks good to me.

File: impl/src/as/mod.rs (hunk 3 above)
Comment (tyranron) [reply impl/src/as/mod.rs]: @JelteF good catch 👍

**Comment by tyranron** [comment]
ping @JelteF (needs approve)

**Review by JelteF — APPROVED** [review]
