### PR TITLE
Fix raw identifiers usage in `Display`/`Debug` derives (#431)

### LINKED ISSUE #431: Raw identifiers do not work inside generic types
Both of the following generate a working impl:

```rust
#[derive(Display)]
#[display("{thing}")]
struct Struct<T> {
    thing: T,  // generic
}
```

```rust
#[derive(Display)]
#[display("{thing}")]
struct Struct {
    r#thing: i32,  // raw
}
```

but this generates an impl that does not compile.

```rust
#[derive(Display)]
#[display("{thing}")]
struct Struct<T> {
    r#thing: T,  // raw, generic
}
```

```console
error[E0277]: `T` doesn't implement `derive_more::Display`
 --> src/main.rs:3:10
  |
3 | #[derive(Display)]
  |          ^^^^^^^ `T` cannot be formatted with the default formatter
  |
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: required for `&T` to implement `derive_more::Display`
  = note: this error originates in the derive macro `Display` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `T` with trait `Display`
  |
5 | struct Struct<T: derive_more::Display> {
  |                ++++++++++++++++++++++
```

### PR DESCRIPTION
**Pull request by tyranron**
Resolves #431

## Synopsis

See https://github.com/JelteF/derive_more/issues/431#issue-2761055237:
> Both of the following generate a working impl:
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct<T> {
>     thing: T,  // generic
> }
> ```
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct {
>     r#thing: i32,  // raw
> }
> ```
> 
> but this generates an impl that does not compile.
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct<T> {
>     r#thing: T,  // raw, generic
> }
> ```
> 
> ```
> error[E0277]: `T` doesn't implement `derive_more::Display`
>  --> src/main.rs:3:10
>   |
> 3 | #[derive(Display)]
>   |          ^^^^^^^ `T` cannot be formatted with the default formatter
>   |
>   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
>   = note: required for `&T` to implement `derive_more::Display`
>   = note: this error originates in the derive macro `Display` (in Nightly builds, run with -Z macro-backtrace for more info)
> help: consider restricting type parameter `T` with trait `Display`
>   |
> 5 | struct Struct<T: derive_more::Display> {
>   |                ++++++++++++++++++++++
> ```

## Solution

Consider field with raw identifiers correctly in transparency checks and dereferencing.

## Checklist

- [x] ~~Documentation is updated~~ (not required)
- [x] Tests are added/updated
- [x] [CHANGELOG entry](/CHANGELOG.md) is added

### CODE REVIEW

**Comment by tyranron** [comment]
ping @JelteF

File: tests/debug.rs [hunk 1]
```diff
@@ -1820,6 +1820,81 @@ mod generic {
...
+        #[derive(Debug)]
+        enum Enum<T> {
+            One { r#thing: T },
+        }
+
+        #[test]
+        fn assert() {
+            assert_eq!(
+                format!("{:?}", StructOne::<u8> { r#thing: 8 }),
+                "StructOne { r#thing: 8 }"
```
Comment (JelteF) [inline tests/debug.rs:1843]: shouldn't this be:

```suggestion
                "StructOne { thing: 8 }"
```

i.e. what does std do here?

File: tests/debug.rs [hunk 2]
```diff
@@ -1820,6 +1820,81 @@ mod generic {
...
 
+    mod raw {
+        #[cfg(not(feature = "std"))]
+        use alloc::format;
+
+        use derive_more::Debug;
+
+        #[derive(Debug)]
+        struct StructOne<T> {
+            r#thing: T,
```
Comment (JelteF) [inline tests/debug.rs:1831]: I think we should also have a test for the case where the `r#` is actually needed, like for a keyword such as `r#struct`

File: tests/debug.rs (hunk 1 above)
Comment (tyranron) [reply tests/debug.rs:1843]: @JelteF nice catch 👍

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9e4490c4d098257a889a6c70d4f90808

**Comment by tyranron** [comment]
@JelteF done!

**Review by JelteF — APPROVED** [review]
