### PR TITLE
Replace `fn backtrace()` with `Provider` API in `Error` derive

### LINKED ISSUE #195: backtrace method was removed by Rust
@tyranron @ilslv The tests started failing with the most recent rust nightlies because of this: https://github.com/rust-lang/rust/pull/99431

Could you spend some time to fix it and use the Provider API instead? https://github.com/rust-lang/rust/issues/96024

I wanted to release version 1.0.0 of derive_more but this blocks me from doing that.

### PR DESCRIPTION
**Pull request by ilslv**
Fixes #195 similar to https://github.com/dtolnay/thiserror/pull/182

### CODE REVIEW

**Review by tyranron — APPROVED** [review]

**Comment by tyranron** [comment]
@JelteF would you be so kind to move requirement from `Test Rust 1.36.0` CI jobs to `Test Rust 1.56.0` in `master` branch protection settings?

**Review by tyranron — CHANGES_REQUESTED** [review]
@ilslv hmm...regarding the CI failure. I thought it was because of my changes, but I can reproduce the same test failures localy on your last commit in `2022-09-08` nightly Rust. Could you look into it?

File: tests/error/nightly/mod.rs [hunk 1]
```diff
@@ -86,6 +86,8 @@ impl Default for BacktraceErr {
 
 impl Error for BacktraceErr {
     fn provide<'a>(&'a self, demand: &mut std::any::Demand<'a>) {
-        demand.provide_ref(&self.backtrace).provide_value(|| 42);
+        demand
+            .provide_ref::<Backtrace>(&self.backtrace)
+            .provide_value::<i32>(42);
```
Comment (ilslv) [inline tests/error/nightly/mod.rs:91]: @tyranron downside of using nightly is that [API can change at any time][1] 🙃 

[1]: https://github.com/rust-lang/rust/pull/99583/files#diff-0752889661748b8a15a597d7156127b6fb90fdeda0627be50e07f3f785bd0f4dR799

Comment (tyranron) [reply tests/error/nightly/mod.rs:91]: @ilslv let's see for a while how it will play.

**Review by tyranron — APPROVED** [review]

File: doc/error.md [hunk 2]
```diff
@@ -90,17 +90,32 @@ enum CompoundError {
...
+        #[error(backtrace, source)]
+        explicit_source: WithSource,
+    },
     Tuple(WithExplicitSource),
     WithoutSource(#[error(not(source))] Tuple),
 }
 
 fn main() {
     assert!(Simple.source().is_none());
-    assert!(Simple.backtrace().is_none());
```
Comment (JelteF) [inline doc/error.md:103]: The doc text above still mentions the backtrace method. This should be changed to talk about this `any::request_ref::<Backtrace>()` function

File: src/error.rs [hunk 3]
```diff
@@ -203,16 +199,67 @@ impl<'input, 'state> ParsedFields<'input, 'state> {
...
+            }
+        });
+        let backtrace_provider = self
+            .source
+            .filter(|source| *source == backtrace)
+            .is_none()
+            .then(|| {
+                let backtrace_expr = &self.data.members[backtrace];
+                quote! {
+                    demand.provide_ref::<std::backtrace::Backtrace>(&#backtrace_expr);
```
Comment (JelteF) [inline src/error.rs:218]: Food for thought: One of the reasons for this provider API (afaict) is so more types can be provided that just Backtrace, without needing to add more methods to the `Error` trait. 

So probably we want to allow this too, e.g. to embed some additionaly context such as trace IDs in there for distributed tracing. This would probabyl be better as a separate PR. I think it makes sense to keep dedicated and easy to use support for the `Backtrace` type.

Another idea is to also provide the `source` through the provider API, like is done in the rust docs

```rust
impl std::error::Error for Error {
    fn provide<'a>(&'a self, demand: &mut Demand<'a>) {
        demand
            .provide_ref::<MyBacktrace>(&self.backtrace)
            .provide_ref::<dyn std::error::Error + 'static>(&self.source);
    }
}
```
Source: https://doc.rust-lang.org/nightly/std/error/trait.Error.html

**Review by JelteF — CHANGES_REQUESTED** [review]
Looks good overall. but docs need to be updated. Thanks for all the work on this.

File: src/error.rs (hunk 3 above)
Comment (ilslv) [reply src/error.rs:218]: @JelteF I've already [raised question of what should be provided][1] and this implementation mirrors [`thiserror`][2]. As `Provider` API is quite new and `source()` default impl still returns `None`, I think that we shouldn't rush with providing `dyn Error` and wait how `Provider` API will be used throughout the ecosystem. 




[1]: https://github.com/JelteF/derive_more/issues/195#issuecomment-1231616625
[2]: https://github.com/dtolnay/thiserror/pull/182

**Comment by tyranron** [comment]
@JelteF ping

**Review by JelteF — APPROVED** [review]
